
/*
Fichier : Creation_GroupeM.sql
Auteurs : 
Antoine AFFLATET 
Mohamed MASBAH ABOU LAICH 21611213
Nom du groupe : M
*/

/*
A METTTRE OBLIGATOIREMENT AU DEBUT 
- SUPPRESSION DE LA BASE DE DONNEES
- CREATION DE LA BASE DE DONNEES
- SUPPRESSIONS DE TOUTES LES BASES CREEES POUR LE PROJET
*/
DROP DATABASE IF EXISTS MyEvents;
CREATE DATABASE  MyEvents;
USE MyEvents;

/*
Création de la base de  données
*/

DROP TABLE IF EXISTS UTILISATEUR;
DROP TABLE IF EXISTS CONTRIBUTEUR;
DROP TABLE IF EXISTS ADMINISTRATEUR;
DROP TABLE IF EXISTS VISITEUR;
DROP TABLE IF EXISTS COMPTES;
DROP TABLE IF EXISTS THEMES;
DROP TABLE IF EXISTS EVENEMENTS;
DROP TABLE IF EXISTS INSCRIT;
-- **************************************   UTILISATEUR  

CREATE TABLE   UTILISATEUR  
(
   U_ID            int(11) AUTO_INCREMENT NOT NULL,
   ROLE            VARCHAR(45) NOT NULL, /* 3 ROLES SEULEMENT : admin / contributeur / visiteur*/
   PSEUDO	   VARCHAR(45) NOT NULL,
   EMAIL           varchar(150) NOT NULL ,

CONSTRAINT USR_PK PRIMARY KEY ( U_ID )

);

-- **************************************  CONTRIBUTEUR 

CREATE TABLE  AJOUT_CONTRIB 
(
  C_ID         INT(11) NOT NULL ,
  ADMIN_ID      INT(11)  NOT NULL ,

CONSTRAINT CONTRIB_PK PRIMARY KEY ( C_ID,ADMIN_ID ),
CONSTRAINT  CONTRIB_ID_FK FOREIGN KEY( C_ID ) REFERENCES  UTILISATEUR  ( U_ID ),
CONSTRAINT  CONTRIB_ADMIN_ID_FK FOREIGN KEY( ADMIN_ID ) REFERENCES  UTILISATEUR  ( U_ID )
);


/*
-- **************************************   VISITEUR  

CREATE TABLE   VISITEUR  
(
   V_ID   numeric NOT NULL ,
   
CONSTRAINT VISIT_PK PRIMARY KEY ( V_ID ),
CONSTRAINT VISIT_ID_FK FOREIGN KEY(  V_ID  ) REFERENCES   UTILISATEUR   (  U_ID  )

);



-- **************************************  ADMIN 

CREATE TABLE  ADMINISTRATEUR 
(
  A_ID  numeric NOT NULL ,

CONSTRAINT ADMIN_PK PRIMARY KEY ( A_ID ),
CONSTRAINT  ADMIN_FK FOREIGN KEY ( A_ID ) REFERENCES  UTILISATEUR  ( U_ID )
);
*/

-- **************************************  COMPTES 

CREATE TABLE  COMPTES 
(
  ID_COMPTE   INT(11) NOT NULL AUTO_INCREMENT ,
  USER_ACCOUNT_ID INT(11)  NOT NULL,
  PASSWORD  varchar(45) NOT NULL ,
  
CONSTRAINT COMPTES_PK PRIMARY KEY ( ID_COMPTE ),
CONSTRAINT  COMPTES_USR_FK FOREIGN KEY ( USER_ACCOUNT_ID ) REFERENCES  UTILISATEUR  ( U_ID )
);


-- **************************************   THEME  

CREATE TABLE   THEME  
(
   ID_THEME      varchar(45) NOT NULL ,
   NOM           varchar(45) NOT NULL ,

CONSTRAINT THEME_PK PRIMARY KEY ( ID_THEME )
);



-- **************************************  EVENEMENTS 
/* ON CONSIDERE QUE SI  LE NOMBRE DE PLACE EST NULL 
LE NOMBRE DE PLACE EN VRAI EST ILLIMITÉ*/

CREATE TABLE EVENEMENTS
(
  E_ID             varchar(45) NOT NULL ,
  CREATEUR_ID        INT(11)	  NOT NULL ,
  TITRE_EVENEMENTS  varchar(45) NOT NULL ,
  ADRESSE           varchar(45) NOT NULL ,
  DATE_DEBUT        date NOT NULL ,
  DATE_FIN          date NOT NULL ,
  NBR_DE_PLACE      NUMERIC,
  ID_THEME          varchar(45) NOT NULL ,


CONSTRAINT EVENT_PK PRIMARY KEY ( E_ID ),

CONSTRAINT  THEME_EVT_FK  FOREIGN KEY ( ID_THEME ) REFERENCES  THEME( ID_THEME ),
CONSTRAINT  CREATOR_EVT_FK  FOREIGN KEY ( CREATEUR_ID ) REFERENCES UTILISATEUR ( U_ID )
);


CREATE TABLE  INSCRIT 
(
 ID_INSCRIPTION INT(11) NOT NULL AUTO_INCREMENT,	
  ID_USER   INT(11) NOT NULL ,
  ID_EVENEMENT varchar(45) NOT NULL ,

CONSTRAINT INSCRIT_PK PRIMARY KEY ( ID_INSCRIPTION ),
CONSTRAINT  INSCRIT_USR_FK FOREIGN KEY ( ID_USER ) REFERENCES  UTILISATEUR  ( U_ID ),
CONSTRAINT  INSCRIT_EVENT_FK FOREIGN KEY ( ID_EVENEMENT ) REFERENCES  EVENEMENTS  ( E_ID )

);

CREATE TABLE LOGERROR  (
  ID INT(11) AUTO_INCREMENT,
  MESSAGE VARCHAR(255) DEFAULT NULL,
  THETIME TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_LOGERROR PRIMARY KEY (ID)
);	



/* ------------------------------------
Insertion de tuples dans les relations
--------------------------------------*/

INSERT INTO UTILISATEUR (ROLE,PSEUDO , EMAIL ) VALUES ('ADMIN','SENTES','antoine.afflatet@gmail.com');
INSERT INTO UTILISATEUR ( ROLE , PSEUDO , EMAIL ) VALUES ('ADMIN','MOMOMOAN852','momo.man@gmail.com');
INSERT INTO UTILISATEUR ( ROLE , PSEUDO , EMAIL ) VALUES ('CONTRIBUTEUR','RYU','RYU.PAJ@gmail.com');
INSERT INTO UTILISATEUR (ROLE , PSEUDO , EMAIL ) VALUES ( 'CONTRIBUTEUR','TANAKA','TANA.KA@gmail.com');
INSERT INTO UTILISATEUR ( ROLE , PSEUDO , EMAIL ) VALUES ('CONTRIBUTEUR','GON','GON.HUNTER@gmail.com');
INSERT INTO UTILISATEUR ( ROLE , PSEUDO , EMAIL ) VALUES ('VISITEUR','KARIMON','kari.mon@gmail.com');
INSERT INTO UTILISATEUR ( ROLE , PSEUDO , EMAIL ) VALUES ('VISITEUR','DORAIMON','dora.imon@gmail.com');
INSERT INTO UTILISATEUR ( ROLE , PSEUDO , EMAIL ) VALUES ('VISITEUR','dass','saleh.dassouki@gmail.com');

INSERT INTO AJOUT_CONTRIB(C_ID,ADMIN_ID) SELECT U2.U_ID,U1.U_ID FROM UTILISATEUR U1,UTILISATEUR U2 WHERE U1.U_ID = 1 AND U2.ROLE = 'CONTRIBUTEUR';

INSERT INTO COMPTES( USER_ACCOUNT_ID , PASSWORD ) VALUES (1,'ADMIN');
INSERT INTO COMPTES( USER_ACCOUNT_ID , PASSWORD ) VALUES (2,'ADMIN');


INSERT INTO THEME VALUES ('1','CULTURE');
INSERT INTO THEME VALUES ('2','SPORT');


INSERT INTO EVENEMENTS VALUES ('1',3,'VISITE DE MUSEE','MONTPELLIER','11-02-2019','11-03-2019',NULL,'1');
INSERT INTO EVENEMENTS VALUES ('2',3,'VISITE DE MUSEE','PARIS','13-02-2019','14-02-2019',8,'1');

INSERT INTO EVENEMENTS VALUES ('3',4,'TOURNOI DE FOOT','MONTPELLIER','11-01-2020','13-01-2020',NULL,'2');


INSERT INTO INSCRIT(ID_USER,ID_EVENEMENT) VALUES (6,'1');
INSERT INTO INSCRIT(ID_USER,ID_EVENEMENT) VALUES (6,'3');
INSERT INTO INSCRIT(ID_USER,ID_EVENEMENT) VALUES (7,'1');

